name: precomputation
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - hdf5
  - keras-applications
  - keras-preprocessing
  - matplotlib
  - matplotlib-base
  - numpy
  - pickleshare
  - pillow
  - scikit-learn
  - scipy
  - seaborn
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - pip
  - pip:
    - albumentations
